### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by KernelTimes** [eouia/MMM-DailyAlarm#1]
Please clarify about how does notification works

**Comment by eouia** [comment]
```
{
        time: "18:00:00",
        beforeText: "Go Home",
        alarmNotification: {
          notification: "SHOW_ALERT",
          payload: {
            message: "I'm going home!!!",
          }
        }
      },
```
In this case, At 18:00, "SHOW_ALERT" notification will be delivered to other modules with payload `{message:"I'm going home!!!"}`.

**Comment by KernelTimes** [comment]
the notification doesnot hide it self. what should i do

**Comment by eouia** [comment]
You mean `message` of `alert` module?
That code was just sample. See the docs of `alert` module.
https://github.com/MichMich/MagicMirror/tree/master/modules/default/alert
You can use `timer` for displaying time.

```
{
        time: "18:00:00",
        beforeText: "Go Home",
        alarmNotification: {
          notification: "SHOW_ALERT",
          payload: {
            message: "I'm going home!!!",
            timer: 1000 * 10,
          }
        }
      },
```

**Comment by KernelTimes** [comment]
i tried but it doesnot seem to work

**Comment by eouia** [comment]
It will disappear after 1000*10 milsec. (10sec)
Or you can hide it by force with another notification "HIDE_ALERT"
